# This configuration file is part of the Hissp source code repository,
# copyright 2019, 2021 Matthew Egan Odendahl
# SPDX-License-Identifier: Apache-2.0
name: Test package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements-dev.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - uses: actions/setup-node@v1
    - name: Lint with parlinter
      run: |
        npm install -g parlinter
        parlinter --trim --write "**/*.lissp"
        git diff
        git reset --hard
        parlinter --list-different "**/*.lissp"
    - name: Create Hissp package
      run: |
        pip install setuptools
        cd setup
        python setup.py sdist
    - name: Install Hissp package from dist/
      run: |
        pip install setup/dist/hissp-*.tar.gz
    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Test install with pytest (including doctests)
      run: |
        python -c "import tests"  # Compiles hissp.basic on package import.
        pytest -v --cov=hissp --cov-report=xml --doctest-modules --doctest-glob *.md tests/ docs/ $(python -c "import hissp; print(hissp.__path__[0])")
    - name: Codecov
      uses: codecov/codecov-action@v1.0.4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
